### ISSUE TITLE
Server down 

### ISSUE THREAD

**Issue by Kristinica** [Kristinica/Bugs#1]
**ENVIRONMENT** Production
 URL: https://peviitor.ro
 browser: Chrome

**STEPS TO REPRODUCE**:
 1. open URL in browser
 2. check the website

**EXPECTED RESULTS:**
 the webpage is loaded without any errors

**ACTUAL RESULTS**:
  no results are shown; no cities are shown; no countries are shown; serve down

**Comment by sebiboga** [comment]
I fixed this issue; please RETEST!

**Comment by Kristinica** [comment]
Retested today in production.
This issue has been fixed.
Closing the bug.
